/**
 * 114 đơn vị hành chính cấp xã của TP Hải Phòng SAU SÁP NHẬP (Nghị quyết 1669/NQ-UBTVQH15, hiệu lực
 * 01/07/2025): 45 phường · 67 xã · 2 đặc khu (Cát Hải, Bạch Long Vĩ) — gồm cả phần Hải Dương cũ.
 *
 * Chủ nhà 01/10/2026: "Phường xã: dropdown list kèm tìm kiếm các phường ở Hải Phòng (sau sát nhập)".
 * Nguồn: đối chiếu hai bộ dữ liệu độc lập (vietnam-address-database theo NQ 202/2025, vietnam-address-data)
 * — cùng 114 tên, chỉ khác kiểu bỏ dấu (Hoà/Hòa); giữ kiểu "òa" như phần còn lại của ứng dụng.
 * Lưu NGUYÊN tên kèm loại ("Phường Hồng Bàng", "Xã An Lão") — có tên trùng giữa phường và xã cũ.
 */

export const WARDS_HAI_PHONG = [
  "Phường Ái Quốc",
  "Phường An Biên",
  "Phường An Dương",
  "Phường An Hải",
  "Phường An Phong",
  "Phường Bắc An Phụ",
  "Phường Bạch Đằng",
  "Phường Chí Linh",
  "Phường Chu Văn An",
  "Phường Đồ Sơn",
  "Phường Đông Hải",
  "Phường Dương Kinh",
  "Phường Gia Viên",
  "Phường Hải An",
  "Phường Hải Dương",
  "Phường Hòa Bình",
  "Phường Hồng An",
  "Phường Hồng Bàng",
  "Phường Hưng Đạo",
  "Phường Kiến An",
  "Phường Kinh Môn",
  "Phường Lê Chân",
  "Phường Lê Đại Hành",
  "Phường Lê Ích Mộc",
  "Phường Lê Thanh Nghị",
  "Phường Lưu Kiếm",
  "Phường Nam Đồ Sơn",
  "Phường Nam Đồng",
  "Phường Nam Triệu",
  "Phường Ngô Quyền",
  "Phường Nguyễn Đại Năng",
  "Phường Nguyễn Trãi",
  "Phường Nhị Chiểu",
  "Phường Phạm Sư Mạnh",
  "Phường Phù Liễn",
  "Phường Tân Hưng",
  "Phường Thạch Khôi",
  "Phường Thành Đông",
  "Phường Thiên Hương",
  "Phường Thủy Nguyên",
  "Phường Trần Hưng Đạo",
  "Phường Trần Liễu",
  "Phường Trần Nhân Tông",
  "Phường Tứ Minh",
  "Phường Việt Hòa",
  "Xã An Hưng",
  "Xã An Khánh",
  "Xã An Lão",
  "Xã An Phú",
  "Xã An Quang",
  "Xã An Thành",
  "Xã An Trường",
  "Xã Bắc Thanh Miện",
  "Xã Bình Giang",
  "Xã Cẩm Giang",
  "Xã Cẩm Giàng",
  "Xã Chấn Hưng",
  "Xã Chí Minh",
  "Xã Đại Sơn",
  "Xã Đường An",
  "Xã Gia Lộc",
  "Xã Gia Phúc",
  "Xã Hà Bắc",
  "Xã Hà Đông",
  "Xã Hà Nam",
  "Xã Hà Tây",
  "Xã Hải Hưng",
  "Xã Hồng Châu",
  "Xã Hợp Tiến",
  "Xã Hùng Thắng",
  "Xã Kẻ Sặt",
  "Xã Khúc Thừa Dụ",
  "Xã Kiến Hải",
  "Xã Kiến Hưng",
  "Xã Kiến Minh",
  "Xã Kiến Thụy",
  "Xã Kim Thành",
  "Xã Lạc Phượng",
  "Xã Lai Khê",
  "Xã Mao Điền",
  "Xã Nam An Phụ",
  "Xã Nam Sách",
  "Xã Nam Thanh Miện",
  "Xã Nghi Dương",
  "Xã Nguyễn Bỉnh Khiêm",
  "Xã Nguyên Giáp",
  "Xã Nguyễn Lương Bằng",
  "Xã Ninh Giang",
  "Xã Phú Thái",
  "Xã Quyết Thắng",
  "Xã Tân An",
  "Xã Tân Kỳ",
  "Xã Tân Minh",
  "Xã Thái Tân",
  "Xã Thanh Hà",
  "Xã Thanh Miện",
  "Xã Thượng Hồng",
  "Xã Tiên Lãng",
  "Xã Tiên Minh",
  "Xã Trần Phú",
  "Xã Trường Tân",
  "Xã Tứ Kỳ",
  "Xã Tuệ Tĩnh",
  "Xã Việt Khê",
  "Xã Vĩnh Am",
  "Xã Vĩnh Bảo",
  "Xã Vĩnh Hải",
  "Xã Vĩnh Hòa",
  "Xã Vĩnh Lại",
  "Xã Vĩnh Thịnh",
  "Xã Vĩnh Thuận",
  "Xã Yết Kiêu",
  "Đặc khu Bạch Long Vĩ",
  "Đặc khu Cát Hải",
] as const

export type WardHaiPhong = (typeof WARDS_HAI_PHONG)[number]
